config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, controllers: {registrations: "registrations"}

  resources :schedules

  resources :users do
    resources :schedules, except: [:new, :create, :show]
  end

  get "repeats/confirm"
  resources :repeats, only: [:destroy]

  namespace :api do
    resources :my_schedules, only: :index
    resources :shared_schedules, only: :index
    resources :schedules, only: :index
  end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  include ScheduleJson
  include RailsAdminSchedule
  require "sidekiq/api"

  QUERY = "(start_time <= :start_time AND finish_time >= :finish_time)
            OR (start_time > :start_time AND start_time < :finish_time)
            OR (finish_time > :start_time AND finish_time < :finish_time)"

  belongs_to :repeat
  belongs_to :room
  belongs_to :user

  has_many :members, class_name: "User", through: :schedule_users, foreign_key: :schedule_id
  has_many :schedule_users

  validates :finish_time, presence: true
  validates :start_time, presence: true
  validates :title, presence: true, length: {maximum: 150}
  validates :user, presence: true
  validate :valid_time
  validate :valid_room, if: :room_id

  scope :with_room, ->(room, id){where(room: room).where.not id: id}
  scope :order_start_time, ->{order start_time: :asc}
  scope :filte_timer, ->(start, finish){where(QUERY, start_time: start, finish_time: finish)}
  scope :today_schedule, ->{where("start_time LIKE ?", "%#{Time.now.to_date.to_s}%")}
  scope :filter_by_room, ->(room_id) do
    if Settings.no_room == room_id
      where room_id: nil
    else
      where room_id: room_id if room_id.present?
    end
  end
  scope :my_schedule, ->user_id{where(" ? <= finish_time AND user_id = ?", Time.zone.now, user_id)}
  scope :shared_schedules_future, ->user_id{joins(:schedule_users)
                                      .where(" ? <= finish_time AND schedule_users.user_id = ?", Time.zone.now, user_id)}
  scope :shared_schedules, ->user_id{joins(:schedule_users).where(" schedule_users.user_id = ?", user_id)}
  scope :filter_by_user, ->user_id{where user: user_id}
  scope :search_by_time, ->(_start, _end) do
    if _start.present? && _end.present?
      where("DATE_FORMAT(start_time,'%Y-%m-%d') BETWEEN ? AND ? ", _start, _end)
    elsif _start.present? && !_end.present?
      where("DATE_FORMAT(start_time,'%Y-%m-%d') >= ?", _start)
    elsif !_start.present? && _end.present?
      where("DATE_FORMAT(start_time,'%Y-%m-%d') <= ?", _end)
    end
  end
  scope :shared_and_my_schedules, ->user_id{joins("LEFT JOIN schedule_users ON schedules.id = schedule_users.schedule_id")
                                      .where(" schedules.user_id = ? OR schedule_users.user_id = ?", user_id, user_id)}
  scope :filter_by_repeat, ->repeat_id{where repeat: repeat_id}
  scope :with_ids, ->ids{where id: ids}

  delegate :color, :name, to: :room, prefix: true, allow_nil: true

  after_commit :announce_upcoming_event, on: :create, if: :announced_before
  after_commit :announce_event_after_update, on: :update, if: :announced_before
  after_commit :delete_job, on: :destroy

  def self.search options = {}, user_id
    _start, _end = options[:start_date].to_date, options[:end_date].to_date
    _room = options[:room_id]
    search = Schedule.shared_and_my_schedules(user_id).ransack options

    search.result.search_by_time(_start, _end).filter_by_room(_room).uniq
  end

  def have_important_changes
    (important_attributes & self.previous_changes.keys).present?
  end

  private
  def important_attributes
    [:room_id, :description, :start_time, :finish_time]
  end

  def valid_room
    if Schedule.with_room(room_id, id).filte_timer(start_time, finish_time).count > 0
      errors.add :room, I18n.t("valid.room")
    end
  end

  def valid_time
    return if start_time.blank? || finish_time.blank?

    errors.add :base, I18n.t("invalid.create_in_past") if start_time < Time.zone.now
    errors.add :base, I18n.t("invalid.between_time") unless cover_in_time?
    errors.add :base, I18n.t("invalid.time") if valid_min_time_range?
  end

  def announce_upcoming_event
    announced_at = start_time.ago announced_before
    AnnounceWorker.perform_at(announced_at, id) if Time.zone.now < announced_at
  end

  def delete_job
    jobs = Sidekiq::ScheduledSet.new
    jobs.each{|job| job.delete if job.klass == "AnnounceWorker" && job.args[0] == id}
  end

  def announce_event_after_update
    delete_job
    announce_upcoming_event
  end

  def time_range
    beginning_of_day = start_time.change({hour: 7, minute: 0})
    end_of_day = start_time.change({hour: 21, minute: 0})
    (beginning_of_day..end_of_day)
  end

  def cover_in_time?
    time_range.cover?(start_time) && time_range.cover?(finish_time)
  end

  def valid_min_time_range?
    (finish_time - start_time) < Settings.schedule.min_time
  end
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < Admin::BaseController
  respond_to :html, :js

  def index
    @schedules = Schedule.page(params[:page]).per Settings.per_page_list_schedule
    @today_schedules = Schedule.today_schedule
  end

  def update
    @schedule = Schedule.find params[:id]
    @schedule.update_attributes state: params[:state]
  end

  private
  def schedule_params
    params.require(:schedule).permit :state
  end
end

app/controllers/api/schedules_controller.rb
class Api::SchedulesController < ApplicationController
  load_and_authorize_resource

  def index
    schedules = Schedule.filter_by_room params[:room_id]

    respond_to do |format|
      format.json {render json: {schedules: schedules.map(&:min_json)}, status: :ok}
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:share_schedules]
      @schedules = Schedule.shared_schedules current_user.id
    elsif params[:search_form]
      @schedules = Schedule.search params[:search_form], current_user.id 
    else
      @schedules = Schedule.filter_by_user current_user
    end
  end

  def show
  end

  def new
    @users = User.without_user(current_user.id).pluck :name, :id
    decode_and_assign_value if params[:data]
  end

  def create
    @users = User.without_user(current_user.id).pluck :name, :id
    @schedule.user = current_user

    if @schedule.save
      repeat_type = params[:repeat]

      if repeat_type.present?
        RepeatWorker.perform_async @schedule.id, repeat_type
      else
        added_member_ids = @schedule.member_ids
        MembersInvitationWorker.perform_async added_member_ids, [@schedule.id]
      end

      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      respond_to do |format|
        format.html {render :new}
        format.js
      end
    end
  end

  def edit
    @users = User.without_user(current_user.id).pluck :name, :id
  end

  def update
    old_member_ids = @schedule.member_ids
    @users = User.without_user(current_user.id).pluck :name, :id

    if @schedule.update_attributes schedule_params
      new_member_ids = @schedule.member_ids
      added_member_ids = new_member_ids - old_member_ids
      removed_member_ids = old_member_ids - new_member_ids
      schedule_id = @schedule.id
      announce = @schedule.have_important_changes

      if params[:edit_repeat].present?
        EditRepeatWorker.perform_async schedule_id, announce, added_member_ids, removed_member_ids
      else
        shared_member_ids = new_member_ids & old_member_ids
        UpdatedEventsAnnouncementWorker.perform_async(shared_member_ids, [schedule_id]) if announce
        MembersInvitationWorker.perform_async added_member_ids, [schedule_id]
        RemovedMembersAnnouncementWorker.perform_async removed_member_ids, [schedule_id]
      end

      flash[:success] = t("flash.update")
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy

    unless params[:user_id]
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  private
  def schedule_params
    params.require(:schedule).permit :title, :start_time, :finish_time, :description, :room_id, :announced_before, member_ids: []
  end

  def decode_and_assign_value
    data = Base64.decode64 params[:data]
    data = JSON.parse data
    @schedule.start_time = format_datetime data["start_time"]
    @schedule.finish_time = format_datetime data["finish_time"]
    @schedule.title = data["title"]
  end

  def format_datetime datetime
    datetime.to_datetime().strftime "%Y-%m-%d %H:%M"
  end
end

app/views/schedules/_form.html.erb
<%= form_for @schedule do |f| %>
  <div class="btn-form">
    <%= link_to "", root_path, class: "btn btn-primary back-btn glyphicon glyphicon-arrow-left", title: t("button.title.back") %>
    <%= f.submit t("schedules.form.submit"), class: "btn btn-primary btn-submit" %>
  </div>
  <%= render "shared/error_messages", object: f.object %>
  <div class="col-md-12 well">
    <div class="col-md-12">
      <%= f.label t("schedules.form.event_name") %>
      <%= f.text_field :title, placeholder: t("schedules.form.event_title"),
        class: "form-control" %>
    </div>
    <div class="col-md-12">
      <br/>
      <div class="col-md-5 start-date">
        <%= f.label t("schedules.form.start_time") %>
        <div>
          <%= f.text_field :start_time,
            placeholder: t("schedules.form.start_time"), style: "width: 300px" %>
        </div>
      </div>
      <div class="col-md-5 col-md-offset-2 finish-date">
        <%= f.label t("schedules.form.finish_time") %>
        <div class="input-group date">
          <%= f.text_field :finish_time,
            placeholder: t("schedules.form.finish_time"), style: "width: 300px" %>
        </div>
      </div>
    </div>

    <% if @schedule.id.nil? %>
      <div class="col-md-12">
        <%= f.label t("schedules.form.repeat") %><br/>
        <% Settings.repeat_types.each do |key, value| %>
          <div class="col-md-1"><%= label_tag value %></div>
          <div class="col-md-1">
            <%= check_box_tag :repeat, key %>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="col-md-12">
      <br/>
      <%= f.label t("schedules.form.room") %><br/>
      <%= f.select :room_id, Room.all.collect{|s| [s.name, s.id]}, {include_blank: t("placeholder.none")}, {class: "select-room form-control"} %>
    </div>

    <div class="col-md-12">
      <br/>
      <%= f.label t("schedules.form.members") %><br/>
      <%= f.select :member_ids, @users, {},
        {class: "select-members form-control", multiple: :multiple} %>
    </div>

    <div class="col-md-12">
      <br/>
      <%= f.label t("schedules.form.announced_before"), class: "left-label" %>
      <%= f.select :announced_before, Settings.announced_before.to_a, {}, class: "room-selector form-control" %>
    </div>

    <div class="col-md-12">
      <br/>
      <%= f.label t("schedules.form.description") %>
      <%= f.text_area :description, placeholder: t("schedules.form.compose_description"),
        class: "form-control" %>
    </div>

    <% if @schedule.id.present? && @schedule.repeat_id.present? %>
      <div class="col-md-7 row">
        <br/>
        <%= f.label t("schedules.form.edit_repeat"), class: "col-md-2" %>
        <%= check_box_tag :edit_repeat, true, false, class: "col-md-1" %>
      </div>

      <%= hidden_field_tag :schedule_id, @schedule.id %>
    <% end %>
  </div>
<% end %>

app/views/schedules/_list_schedules.html.erb
<% @schedules.each do |schedule| %>
  <tr id="event_user_<%= schedule.id %>" <%= "class=repeat-#{schedule.repeat_id}" if schedule.repeat_id.present? %>>
    <td><div class="col-md-12"><%= link_to schedule.title, schedule_path(schedule) %></div></td>
    <td><div class="col-md-12"><%= schedule.room_name %></div></td>
    <td><div class="col-md-12"><%= schedule.start_time.strftime("%d/%m/%Y") %></div></td>
    <td><div class="col-md-12"><%= schedule.start_time.strftime("%H:%M") %></div></td>
    <td><div class="col-md-12"><%= schedule.finish_time.strftime("%H:%M") %></div></td>
    <td>
      <div class="col-md-12" data-no-turbolink="true">
        <% if can? :update, schedule %>
          <%= link_to "", edit_user_schedule_path(current_user, schedule),
            class: "glyphicon glyphicon-edit index-btn-edit", title: t("button.edit") %>
        <% end %>

        <% if can? :destroy, schedule %>
          <%= link_to "", user_schedule_path(current_user, schedule),
            method: :delete, class: "glyphicon glyphicon-trash index-btn-delete", remote: true,
            data: {confirm: t("button.confirm")}, title: t("button.delete") %>
        <% end %>

        <% if schedule.repeat_id.present? %>
          <% if can? :destroy, schedule.repeat %>
            <%= link_to image_tag("btn/delete-repeat.png"), repeat_path(schedule.repeat_id),
              method: :delete, class: "index-btn-delete-repeat", remote: true,
              data: {confirm: t("button.confirm")}, title: t("button.delete_repeat") %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/schedules/_schedule.html.erb
<li>
  <div><b><%= schedule.title %></b></div>
  <p><small><%= t("schedules.form.create_by") %>: <%= schedule.user.name %></small></p>
  <p><%= t("schedules.form.room") %>: <%= schedule.room.name %></p>
  <div>
    <%= t("pages.form.from") %>: <%= schedule.start_time.strftime("%H:%M") %>
    <%= t("pages.form.to") %>: <%= schedule.finish_time.strftime("%H:%M") %>
  </div>
  <%= link_to t("button.detail"), schedule %>
</li>

app/views/schedules/create.js.erb
<% if @schedule.errors.any? %>
  $("#error-messages").html("<%= j(render "shared/quick_error_messages", object: @schedule) %>");
<% else %>
  $("#quick-event-popup").css({"visibility": "hidden"});
  $("form#new_schedule")[0].reset();

  $("#calendar").fullCalendar("unselect");
  $("#calendar").fullCalendar("refetchEvents");

  $.get( "/api/my_schedules", function(data) {
    $("#my_schedules").html(data);
  });
  $.get( "/api/shared_schedules", function(data) {
    $("#shared_schedules").html(data);
  });
<% end %>

app/views/schedules/destroy.js.erb
$("#event_user_<%= @schedule.id %>").remove();
$(".event-<%= @schedule.id %>").remove();
$("#calendar").fullCalendar("refetchEvents");
$("#event-preview-popup").css({"visibility": "hidden"});

$.get( "/api/my_schedules", function(data) {
  $("#my_schedules").html(data);
});

$.get( "/api/shared_schedules", function(data) {
  $("#shared_schedules").html(data);
});

app/views/schedules/edit.html.erb
<% provide :title, t("schedules.edit_event_title") %>
<%= render "form" %>

app/views/schedules/index.html.erb
<% provide :title, t("schedules.index.title") %>
<% if user_signed_in? %>
  <% content_for :btn_new_schedule do %>
    <%= link_to_if(can?(:create, Schedule), t("pages.home.create_event"), new_schedule_path, class: "btn btn-primary") %>
  <% end %>
<% end %>

<h4>
  <span class="btn-form">
    <%= link_to "", root_path, class: "btn btn-primary back-btn glyphicon glyphicon-arrow-left", title: t("button.title.back") %>
  </span>

  <% if params[:share_schedules] %>
    <%= t("schedules.index.title_share_events") %>
  <% elsif params[:search_form] %>
    <%= t("schedules.index.title_search_events") %>
  <% else %>
    <%= t("schedules.index.title_my_events") %>
  <% end %>
</h4>

<table class="table table-hover">
  <tr>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.title") %>
      </div>
    </th>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.room") %>
      </div>
    </th>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.date") %>
      </div>
    </th>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.start") %>
      </div>
    </th>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.finish") %>
      </div>
    </th>
    <th>
      <div class="col-md-12">
        <%= t("schedules.index.listing.action") %>
      </div>
    </th>
  </tr>
  <%= render "list_schedules" %>
</table>

app/views/schedules/new.html.erb
<% provide :title, t("schedules.new.title") %>
<%= render "form" %>

app/views/schedules/show.html.erb
<% provide :title, t("schedules.show.title") %>

<div class="form-actions btn-form" data-no-turbolink="true">
  <%= link_to "", root_path, class: "btn btn-primary back-btn glyphicon glyphicon-arrow-left", title: t("button.title.back") %>
  <% if can? :update, @schedule %>
    <%= link_to t("button.edit"), edit_schedule_path(@schedule), class: "btn btn-primary btn-submit" %>
  <% end %>
  <% if can? :destroy, @schedule %>
    <%= link_to t("button.delete"), schedule_path(@schedule), method: :delete, data: {confirm: t("button.confirm")}, class: "btn btn-danger btn-submit" %>
  <% end %>
</div>

<div class="col-md-12 well">
  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.event_rest") %></label>
    <div class="col-md-10">
      <div class="col-md-12">
        <div id="countdown"></div>
        <%= hidden_field_tag "end-date", @schedule.finish_time.strftime(Settings.date_time_format) %>
      </div>
    </div>
  </div>

  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.event_title") %></label>
    <div class="col-md-10">
      <div class="form-control"><b><%= @schedule.title %></b></div>
    </div>
  </div>

  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.start_time") %></label>
    <div class="col-md-2">
      <div class="form-control"><%= @schedule.start_time.strftime("%d/%m/%Y") %></div>

    </div>
    <div class="col-md-2">
      <div class="form-control"><%= @schedule.start_time.strftime("%H:%M") %></div>
    </div>
      <label class="col-md-2"><%= t("schedules.form.finish_time") %></label>
    <div class="col-md-2">
      <div class="form-control"><%= @schedule.finish_time.strftime("%d/%m/%Y") %></div>
    </div>
      <div class="col-md-2">
      <div class="form-control"><%= @schedule.finish_time.strftime("%H:%M") %></div>
    </div>
  </div>

  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.room") %></label>
    <div class="col-md-10">
      <div class="form-control">
        <%= @schedule.room_name || t("shared.no_room_selected") %>
      </div>
    </div>
  </div>

  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.create_by") %></label>
    <div class="col-md-10">
      <div class="form-control"><%= @schedule.user.name %></div>
    </div>
  </div>

  <div class="col-md-12" style="padding-bottom: 20px">
    <label class="col-md-2"><%= t("schedules.form.description") %></label>
    <div class="col-md-10">
      <div class="form-control"><%= @schedule.description %></div>
    </div>
  </div>

  <div class="col-md-12">
    <label class="col-md-2"><%= t("schedules.form.members") %></label>
    <div class="col-md-10">
      <% @schedule.members.each do |member| %>
        <div class="col-md-6" style="padding-bottom: 5px">
          <%= image_tag "default-user.png", size: "20x20", alt: "Member", class: "img-rounded" %>
          <%= member.name %>
        </div>
      <% end %>
    </div>
  </div>
</div>