config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, controllers: {registrations: "registrations"}

  resources :schedules

  resources :users do
    resources :schedules, except: [:new, :create, :show]
  end

  get "repeats/confirm"
  resources :repeats, only: [:destroy]

  namespace :api do
    resources :my_schedules, only: :index
    resources :shared_schedules, only: :index
    resources :schedules, only: :index
  end
end

app/views/shared/_content_schedule.html.erb
<div>
  <div class="title truncate">
    <span class="glyphicon glyphicon-calendar medium"></span>
    <strong>
      <%= link_to schedule.title, schedule, title: schedule.title %>
    </strong>
  </div>
  <p>
    <%= t("pages.form.date") %>: <%= schedule.start_time.strftime Settings.date_format %>
  </p>
  <p>
    <%= t("pages.form.from") %>: <%= schedule.start_time.strftime Settings.time_format %>
    <%= t("pages.form.to") %>: <%= schedule.finish_time.strftime Settings.time_format %>
  </p>
  <p class="last">
    <%= t("pages.form.room") %>: <%= schedule.room_name %>
  </p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for type %> fade in hide-flash">
    <button class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="child-header" data-no-turbolink="true">
    <%= link_to "Conference Room Booking", root_path, id: "logo" %>
    <% if user_signed_in? %>
      <div class="search-box"><%= render "shared/search_box" %></div>
    <% end %>
    <label class="loading hidden"><%= t("header.loading") %></label>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="profile-image">
              <%= current_user.name %>&nbsp
              <%= image_tag current_user.avatar.url, width: "35", heigth: "35", class: "img-circle" %>
            </div>
          </a>
          <ul class="dropdown-menu menu-profile">
            <% if current_user.super_manager? %>
              <li><%= link_to t("button.super_manager"), rails_admin_path %></li>
            <% end %>
            <li><%= link_to t("button.settings"), edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t("button.logout"), destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t("button.login"), new_user_session_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_quick_error_messages.html.erb
<% if object.errors.any? %>
  <div id="quick_error_explanation" class="quick-error">
    <span type="text" data-toggle="tooltip" data-placement="bottom" title=" <%= object.errors.full_messages.join(" \n ").html_safe %> "><%= t "quick_event.error_msg" %></span>
  </div>
<% end %>

app/views/shared/_search_box.html.erb
<%= form_for :search_form, url: {controller: "schedules", action: "index"}, method: :GET do |f| %>
  <div class="row">
    <div class="col-md-12 col-md-offset-6">
      <div class="input-group" id="adv-search">
        <%= f.text_field :title_cont, class: "form-control text-medium-field", placeholder: t("placeholder.search_schedules") %>
        <div class="input-group-btn">
          <div class="btn-group" role="group">
            <div>
              <button type="button" class="btn btn-default dropdown-toggle medium-field" id="btn-setting">
                <span class="caret"></span>
              </button>
              <div class="dropdown-menu dropdown-menu-right" role="menu"></div>
            </div>
            <%= f.submit t("button.search"), class: "btn btn-primary medium-field btn-search" %>
          </div>
        </div>

        <div id="search-setting" class="col-md-12">
          <div class="search_filter_room">
            <span>
              <%= f.label :room %>
            </span>
            <span>
              <%= f.select :room_id, Room.all.collect {|r| [r.name, r.id]},
                include_blank: t("dropdown.all_room"), class: "form-control small-field" %>
            </span>
          </div>
          <div class="row">
            <div class="lb_date"><%= f.label :date %></div>
            <div class="col-md-5">
              <%= f.text_field :start_date, class: "datepicker form-control small-field",
                placeholder: t("placeholder.start_date"), id: "start_date" %>
            </div>
            <div class="col-md-1 form-to">
              <%= f.label t("pages.form.to") %>
            </div>
            <div class="col-md-5 finish-date">
              <%= f.text_field :end_date, class: "datepicker form-control small-field",
                placeholder: t("placeholder.end_date"), id: "end_date" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="alert alert-warning search-warning"><%= t "flash.warning" %></div>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->